name: test-hardhat-code
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  run-hardhat-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install --save-dev hardhat
      - run: npx hardhat test
